-- action
insert into movies(name,genre,description,actors,year_,img_url) values('Bitkári 2','action','Ex-boxer Zach, talentovaný MMA bojovník Tim, šikanovaný predavač Justin a wrestler Mike pochádzajú z rôznych miest, no spoja sa pre vášeň bojovať a rýchlo sa stanú lojálni k ich neortodoxnému trénerovi Caseovi, skvelému bývalému šampiónovi UFC.
Výučba je oveľa viac než boj. Case pripravuje mladých ľudí na súťaž s názvom Beatdown a tréning prebieha na miestnej vysokej škole s bojovým manažérom Maxom. Nakoniec však budú musieť bojovať proti sebe a nájdu vo vlastných radoch zradcu.',' Michael Jai White; Evan Peters; Jillian Murray; Alex Meraz','2011','./img/movies/bitkari2.jpg');
insert into movies(name,genre,description,actors,year_,img_url) values('Man of Tai Chi','action','Svou režijní prvotinu, MUŽ TAIČI, umístil režisér Keanu Reeves do kulis moderního Pekingu. Film, ve kterém Reeves vytvořil i jednu z hlavních rolí, vypráví o duchovní cestě mladého zápasníka (Tiger Chen), jehož jedinečné schopnosti ho zavádí do prostředí velmi lukrativních nelegálních zápasů. V soubojích, které jsou stále ostřejší, půjde o holý život.','Tiger Chen Hu; Keanu Reeves; Hai Yu; Qing Ye','2013','./img/movies/man-of-tai-chi.jpg');
insert into movies(name,genre,description,actors,year_,img_url) values('Kuriér mafie','action','Kurýr pracující pro místního mafiánského šéfa musí doručit záhadný balíček, zatímco jej pronásleduje skupina neobvyklých gangsterů.',' Dolph Lundgren; Steve Austin; Eric Keenleyside; Mike Dopud','./img/movies/kurier-mafie.jpg');

-- horror
insert into movies(name,genre,description,actors,year_,img_url) values('Paranormal Activity 2','horror','Nevěřili byste, jak strašidelné můžou být záběry z průmyslových kamer. Když před třemi lety debutující režisér Oren Peli představil horor, kde tyto záběry tvořily základní obrazovou složku, málokoho napadlo, že Paranormal Activity vstoupí do historie.',' Brian Boland; Katie Featherston; Sprague Grayden; Micah Sloat','2010','./img/movies/paranormal-activity-2.jpg');
insert into movies(name,genre,description,actors,year_,img_url) values('Nenávisť','horror','Američanka Karen (Sarah Michelle Gellar) študuje v Tokiu za sociálnu pracovníčku a svoj osud si spečatí vo chvíli, keď sa rozhodne zastúpiť istú zdravotnú sestru, ktorá sa jedného dňa z ničoho nič jednoducho neukáže v práci.','Sarah Michelle Gellar; Clea DuVall; William Mapother; Bill Pullman','2004','./img/movies/nenavist.jpg');
insert into movies(name,genre,description,actors,year_,img_url) values('Černobyľské denníky','horror','Černobyl, 1986: Když vypukla nejhorší jaderná katastrofa v dějinách lidstva, evakuovaní obyvatelé blízkého města Pripjať neměli čas ani na to, aby si sbalili osobní věci. O 25 let později šest mladých turistů se svým průvodcem navštěvuje Pripjať, aby tu společně prozkoumali trosky zničeného a zdánlivě opuštěného města. Když je okolnosti přinutí zůstat na místě přes noc, brzy zjišťují, že tu možná nejsou sami.','Jesse McCartney; Jonathan Sadowski; Olivia Dudley; Devin Kelley','2012','./img/movies/chernobyl.jpg');

-- sci-fi
insert into movies(name,genre,description,actors,year_,img_url) values('Akce Bororo','sci-fi','Fantastický příběh o tajemném poslání návštěvnice z jiného světa.','Božidara Turzonovová; Svatopluk Matyáš; Vlastimil Brodský; Zita Kabátová','1972','./img/movies/akce-bororo.jpg');
insert into movies(name,genre,description,actors,year_,img_url) values('The Anomaly','sci-fi','Bývalý voják Ryan Reeve se ocitá v zajetí a probouzí se v nákladním autě, aniž by si pamatoval, jak se tam dostal.','Ian Somerhalder; Alexis Knapp; Noel Clarke; Luke Hemsworth','2014','./img/movies/theanomaly.jpg');
insert into movies(name,genre,description,actors,year_,img_url) values('Hunter Prey','sci-fi','Na neobydlené pouštní planetě ztroskotá vojenská vesmírná loď přepravující nebezpečného vězně cizí vesmírné rasy, který uprchne.','Clark Bartram; Damion Poitier; Sandy Collora; Erin Gray','2009','./img/movies/hunter-prey.jpg');

-- fantasy
insert into movies(name,genre,description,actors,year_,img_url) values('Dračia nevesta','fantasy','Zlý drak unese princeznu Miroslavu uprostřed svatby a uvězní ji na hradě, který stojí na opuštěném ostrově. Princezna přijde o všechno – svou rodinu, přátele i ženicha. Jediné, co jí zbylo, je život v kleci a pravidelné setkání se záhadným mladíkem jménem Arman... jenže co je Arman zač a jak se dostal na drakův opuštěný ostrov? Pravdu se Miroslava dozvídá až příliš pozdě. Láska k dračímu princi je hořká a strašidelná.',' Matvej Lykov; Marija Pojezžajeva; Jola Saňko; Stanislav Ljubšin','2015','./img/movies/on-drakon.jpg');
